/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a2_Jefe_Produccion02;

import static a2_Jefe_Produccion02.PrincipalJefeProduccion.panelPrincipal;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class MantCategorias extends javax.swing.JPanel {

    /**
     * Creates new form MantCategorias
     */
    public MantCategorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BnAñadir = new javax.swing.JButton();
        BnModificar = new javax.swing.JButton();
        BnEliminar = new javax.swing.JButton();

        jLabel1.setText("Mantener Categoria de Produccion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Categoria", "Nombre Categoria"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BnAñadir.setText("Añadir");
        BnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnAñadirActionPerformed(evt);
            }
        });

        BnModificar.setText("Modificar");

        BnEliminar.setText("Eliminar");
        BnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(BnAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(BnEliminar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnAñadir)
                    .addComponent(BnModificar)
                    .addComponent(BnEliminar))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnAñadirActionPerformed
       PanelAñadir n1 = new PanelAñadir();
       n1.setSize(500,500);
       n1.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(n1,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_BnAñadirActionPerformed

    private void BnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnEliminarActionPerformed
        int i=JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar?");
        if (i==0){
           JOptionPane.showMessageDialog(this, "Se elimino correctamente");
           
       }else if(i==1){
           JOptionPane.showMessageDialog(this, "No se elimino ");
           
       }
    }//GEN-LAST:event_BnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BnAñadir;
    private javax.swing.JButton BnEliminar;
    private javax.swing.JButton BnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
