
package a02_JefeProduccion;


/*
SEGUNDO CASO DE USO IMPORTANTE DEL SISTEMA - 
PROCESO DE NEGOCIO: GESTION DE REQUERIMIENTOS DEL CLIENTE
*/
import static a02_JefeProduccion.PrincipalJefeProduccion.panelPrincipal;
import b_metodos_conexion.extraccion_tablas;
import com.toedter.calendar.JCalendar;
import java.awt.BorderLayout;
import b_metodos_conexion.gestion_fechas;
import b_modelos.Produccion;
import b_modelos.criteriosDeCalidad;
import b_modelos.op_produccion;
import b_modelos_para_tablas.UsuarioVSRoles;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.toedter.calendar.JDateChooser;
import java.util.ArrayList;

/**
 *
 * @author pc
 */
public class PanelPreparar extends javax.swing.JPanel {


    public static String textoParaIDRequerimiento = "";
    public static String textoCatSeleccionada = "";

    private ArrayList<UsuarioVSRoles> tabla_vs_usuario_roles = new ArrayList<UsuarioVSRoles>();
    private ArrayList<criteriosDeCalidad> tabla_cc = new ArrayList<criteriosDeCalidad>();
    /**
     * Creates new form PanelPreparar
     */
    public PanelPreparar() {
        
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextoIDR = new javax.swing.JTextField();
        SeleccionarRequerimientos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AsignarRoles = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AsignarCritCalidad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        SeleccionarCatProd = new javax.swing.JButton();
        CrearProduccion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        TextoCP = new javax.swing.JTextField();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setText("ID requerimiento");

        SeleccionarRequerimientos.setText("Seleccionar");
        SeleccionarRequerimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarRequerimientosActionPerformed(evt);
            }
        });

        jLabel3.setText("Trabajadores");

        AsignarRoles.setText("Asignar roles");
        AsignarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarRolesActionPerformed(evt);
            }
        });

        jLabel4.setText("Criterios de calidad");

        AsignarCritCalidad.setText("Asignar criterios de calidad");
        AsignarCritCalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarCritCalidadActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de inicio");

        jLabel6.setText("Urgencia ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Muy urgente", "urgente", "normal" }));

        jLabel7.setText("Categoria de produccion");

        SeleccionarCatProd.setText("Seleccionar Categoria");
        SeleccionarCatProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarCatProdActionPerformed(evt);
            }
        });

        CrearProduccion.setText("Crear Produccion");
        CrearProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProduccionActionPerformed(evt);
            }
        });

        jLabel1.setText("Preparar Produccion");

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AsignarRoles)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TextoIDR, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(SeleccionarRequerimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AsignarCritCalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoCP, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(SeleccionarCatProd)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(CrearProduccion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SeleccionarRequerimientos)
                    .addComponent(TextoIDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(AsignarRoles))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AsignarCritCalidad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionarCatProd)
                    .addComponent(TextoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CrearProduccion)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarCatProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarCatProdActionPerformed
       PanelSeleccionarCategoria pn = new PanelSeleccionarCategoria();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_SeleccionarCatProdActionPerformed

    private void SeleccionarRequerimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarRequerimientosActionPerformed
       PanelSeleccionar pn = new PanelSeleccionar();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
       
    }//GEN-LAST:event_SeleccionarRequerimientosActionPerformed

    private void AsignarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarRolesActionPerformed
       PanelRol pn = new PanelRol();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_AsignarRolesActionPerformed

    private void AsignarCritCalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarCritCalidadActionPerformed
       PanelCriterios pn = new PanelCriterios();
       pn.setSize(500,500);
       pn.setLocation(10,10);
       
       panelPrincipal.removeAll();
       panelPrincipal.add(pn,BorderLayout.CENTER);
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
    }//GEN-LAST:event_AsignarCritCalidadActionPerformed

    
    
    //ANTES DE MOSTRARSE EL JPANEL, SE HARÁN AJUSTES
    //ESTE METODO SIRVE PARA ESO
    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        // TODO add your handling code here:
        TextoIDR.setText(textoParaIDRequerimiento);
        TextoCP.setText(textoCatSeleccionada);

    }//GEN-LAST:event_formAncestorAdded

    private void CrearProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProduccionActionPerformed
        //generar id produccion
        String s = jComboBox1.getSelectedItem().toString();
        //System.out.println(jDateChooser1.getDate());
        String f = gestion_fechas.obtenerFecha(jDateChooser1.getDate());
        
        Produccion p = new Produccion(Integer.parseInt(TextoIDR.getText()),
                Integer.parseInt(TextoCP.getText()), f, s);
        p.guardarBBDD();
        //sacar id produccion}
        extraccion_tablas et= new extraccion_tablas();
        int id_prod_final = Integer.parseInt(et.UltimoElementoID("idProduccion", "produccion"));
        //guardar roles de produccion
        tabla_vs_usuario_roles=PanelRol.tabla_vs_usuario_roles;
        for (int i = 0; i < tabla_vs_usuario_roles.size(); i++) {
            op_produccion opp = new op_produccion (tabla_vs_usuario_roles.get(i).getIduser(),
                    id_prod_final,
                    tabla_vs_usuario_roles.get(i).getRoles());
            opp.guardarBBDD();
        }
        //guardar criterios de calidad
        tabla_cc=PanelCriterios.tablaCriterio;
        for (int i = 0; i < tabla_cc.size(); i++) {
            criteriosDeCalidad cr = new criteriosDeCalidad(id_prod_final,
                    tabla_cc.get(i).getNombre_criterio(),false);
            cr.guardarBBDD();
            
        }
        panelPrincipal.removeAll();
       panelPrincipal.revalidate();
       panelPrincipal.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearProduccionActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1PropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AsignarCritCalidad;
    private javax.swing.JButton AsignarRoles;
    private javax.swing.JButton CrearProduccion;
    private javax.swing.JButton SeleccionarCatProd;
    private javax.swing.JButton SeleccionarRequerimientos;
    public static javax.swing.JTextField TextoCP;
    public static javax.swing.JTextField TextoIDR;
    private javax.swing.JComboBox<String> jComboBox1;
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
